<a href="https://colab.research.google.com/github/nilesh-r-dev/TNS_T170800502_AIML/blob/main/tns_day_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Cleaning and preprocessing

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    "Name": ["Ram", "Shyam", "Ram", "Sita", None,"Shyam","Shyam","Shyam","Ram"],
    "Age": [25, np.nan, 25, 30, 22,13,17,18,19],
    "City": ["Mumbai", "mumbai", "Mumbai", "Delhi", "Delhi", "Delhi", "Delhi", "Delhi", "Delhi"]
}
print(data)
df = pd.DataFrame(data)
df

{'Name': ['Ram', 'Shyam', 'Ram', 'Sita', None, 'Shyam', 'Shyam', 'Shyam', 'Ram'], 'Age': [25, nan, 25, 30, 22, 13, 17, 18, 19], 'City': ['Mumbai', 'mumbai', 'Mumbai', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi']}

    Name   Age    City
0    Ram  25.0  Mumbai
1  Shyam   NaN  mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
4   None  22.0   Delhi
5  Shyam  13.0   Delhi
6  Shyam  17.0   Delhi
7  Shyam  18.0   Delhi
8    Ram  19.0   Delhi

In [ ]:
print(df.head())

    Name   Age    City
0    Ram  25.0  Mumbai
1  Shyam   NaN  mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
4   None  22.0   Delhi

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     8 non-null      float64
 2   City    9 non-null      object
dtypes: float64(1), object(2)
memory usage: 348.0+ bytes

In [ ]:
df.describe()

            Age
count   8.00000
mean   21.12500
std     5.43632
min    13.00000
25%    17.75000
50%    20.50000
75%    25.00000
max    30.00000

In [ ]:
#Identify missing values
df.isnull()

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False  False
3  False  False  False
4   True  False  False
5  False  False  False
6  False  False  False
7  False  False  False
8  False  False  False

In [ ]:
# Count missing values
df.isnull().sum()

Name    1
Age     1
City    0
dtype: int64

In [ ]:
# Drop rows with missing values
df_drop = df.dropna()
df_drop

    Name   Age    City
0    Ram  25.0  Mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
5  Shyam  13.0   Delhi
6  Shyam  17.0   Delhi
7  Shyam  18.0   Delhi
8    Ram  19.0   Delhi

In [ ]:
#  Best Practice

df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Name"] = df["Name"].fillna(df["Name"].mode()[0])
df

    Name     Age    City
0    Ram  25.000  Mumbai
1  Shyam  21.125  mumbai
2    Ram  25.000  Mumbai
3   Sita  30.000   Delhi
4  Shyam  22.000   Delhi
5  Shyam  13.000   Delhi
6  Shyam  17.000   Delhi
7  Shyam  18.000   Delhi
8    Ram  19.000   Delhi

In [2]:
import pandas as pd
import numpy as np
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("data.csv")
df

Saving data.csv to data.csv

,student_id,age,gender,course,year,parent_education,internet_access,hostel_resident,class_type,weather,study_hours,sleep_hours,travel_time_minutes,attendance,absence_reason
0,200.99,17,male,pharmacy,1st year,high school,no,yes,offline,sunny,3.63,7.24,31,1,none
1,200.99,23,other,diploma,2nd year,high school,yes,yes,offline,cloudy,4.39,7.98,50,0,no reason
2,200.99,22,male,b.sc,3rd year,no formal,yes,yes,online,rainy,5.43,6.53,62,1,none
3,200.99,20,other,pharmacy,2nd year,no formal,yes,yes,offline,cloudy,0.21,7.11,63,0,personal work
4,200.99,20,female,pharmacy,1st year,no formal,yes,yes,online,sunny,1.77,9.35,81,0,project work
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19800.01,18,other,bca,4th year,phd,yes,yes,offline,hot,3.10,4.78,25,0,none
19996,19800.01,18,male,ba,3rd year,no formal,yes,no,offline,cloudy,4.95,7.49,68,1,none
19997,19800.01,19,other,pharmacy,2nd year,graduate,yes,yes,offline,rainy,1.01,9.29,72,0,project work
19998,19800.01,19,male,bca,1st year,no formal,yes,no,offline,cold,1.52,7.66,33,0,personal work
19999,19800.01,20,male,b.sc,3rd year,phd,yes,yes,offline,sunny,3.97,5.30,71,1,none

In [3]:
df.head()

,student_id,age,gender,course,year,parent_education,internet_access,hostel_resident,class_type,weather,study_hours,sleep_hours,travel_time_minutes,attendance,absence_reason
0,200.99,17,male,pharmacy,1st year,high school,no,yes,offline,sunny,3.63,7.24,31,1,none
1,200.99,23,other,diploma,2nd year,high school,yes,yes,offline,cloudy,4.39,7.98,50,0,no reason
2,200.99,22,male,b.sc,3rd year,no formal,yes,yes,online,rainy,5.43,6.53,62,1,none
3,200.99,20,other,pharmacy,2nd year,no formal,yes,yes,offline,cloudy,0.21,7.11,63,0,personal work
4,200.99,20,female,pharmacy,1st year,no formal,yes,yes,online,sunny,1.77,9.35,81,0,project work

In [4]:
df.tail()

,student_id,age,gender,course,year,parent_education,internet_access,hostel_resident,class_type,weather,study_hours,sleep_hours,travel_time_minutes,attendance,absence_reason
19995,19800.01,18,other,bca,4th year,phd,yes,yes,offline,hot,3.10,4.78,25,0,none
19996,19800.01,18,male,ba,3rd year,no formal,yes,no,offline,cloudy,4.95,7.49,68,1,none
19997,19800.01,19,other,pharmacy,2nd year,graduate,yes,yes,offline,rainy,1.01,9.29,72,0,project work
19998,19800.01,19,male,bca,1st year,no formal,yes,no,offline,cold,1.52,7.66,33,0,personal work
19999,19800.01,20,male,b.sc,3rd year,phd,yes,yes,offline,sunny,3.97,5.30,71,1,none

In [5]:
df.describe()

,student_id,age,study_hours,sleep_hours,travel_time_minutes,attendance
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,10000.500000,20.473300,2.989558,7.013978,46.978100,0.516350
std,5770.211372,2.284458,1.727470,1.739200,24.583225,0.499745
min,200.990000,17.000000,0.050000,4.060000,5.000000,0.000000
25%,5000.750000,18.000000,1.480000,5.500000,26.000000,0.000000
50%,10000.500000,20.000000,2.980000,7.010000,47.000000,1.000000
75%,15000.250000,22.000000,4.480000,8.540000,68.000000,1.000000
max,19800.010000,24.000000,5.930000,9.940000,89.000000,1.000000

In [6]:
df.isnull()

,student_id,age,gender,course,year,parent_education,internet_access,hostel_resident,class_type,weather,study_hours,sleep_hours,travel_time_minutes,attendance,absence_reason
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [7]:
df.isnull().sum()

student_id             0
age                    0
gender                 0
course                 0
year                   0
parent_education       0
internet_access        0
hostel_resident        0
class_type             0
weather                0
study_hours            0
sleep_hours            0
travel_time_minutes    0
attendance             0
absence_reason         0
dtype: int64

In [8]:
df_drop = df.dropna()
df_drop


00

0

In [10]:
df['age'] = df['age'].fillna(df['age'].mean())

print(df)

       student_id  age  gender    course      year parent_education  \
0          200.99   17    male  pharmacy  1st year      high school
1          200.99   23   other   diploma  2nd year      high school
2          200.99   22    male      b.sc  3rd year        no formal
3          200.99   20   other  pharmacy  2nd year        no formal
4          200.99   20  female  pharmacy  1st year        no formal
...           ...  ...     ...       ...       ...              ...
19995    19800.01   18   other       bca  4th year              phd
19996    19800.01   18    male        ba  3rd year        no formal
19997    19800.01   19   other  pharmacy  2nd year         graduate
19998    19800.01   19    male       bca  1st year        no formal
19999    19800.01   20    male      b.sc  3rd year              phd

      internet_access hostel_resident class_type weather  study_hours  \
0                  no             yes    offline   sunny         3.63
1                 yes             yes    offline  cloudy         4.39
2                 yes             yes     online   rainy         5.43
3                 yes             yes    offline  cloudy         0.21
4                 yes             yes     online   sunny         1.77
...               ...             ...        ...     ...          ...
19995             yes             yes    offline     hot         3.10
19996             yes              no    offline  cloudy         4.95
19997             yes             yes    offline   rainy         1.01
19998             yes              no    offline    cold         1.52
19999             yes             yes    offline   sunny         3.97

       sleep_hours  travel_time_minutes  attendance absence_reason
0             7.24                   31           1           none
1             7.98                   50           0      no reason
2             6.53                   62           1           none
3             7.11                   63           0  personal work
4             9.35                   81           0   project work
...            ...                  ...         ...            ...
19995         4.78                   25           0           none
19996         7.49                   68           1           none
19997         9.29                   72           0   project work
19998         7.66                   33           0  personal work
19999         5.30                   71           1           none

[20000 rows x 15 columns]

In [11]:
df['year'] = df['year'].fillna(df['year'].mode()[0])

print(df['year'].isnull().sum())

0

In [12]:
print(df['year'].unique())

['1st year' '2nd year' '3rd year' '4th year']

In [13]:
print(df.columns.tolist())

['student_id', 'age', 'gender', 'course', 'year', 'parent_education', 'internet_access', 'hostel_resident', 'class_type', 'weather', 'study_hours', 'sleep_hours', 'travel_time_minutes', 'attendance', 'absence_reason']

In [16]:
# Convert gender to lowercase
df['gender'] = df['gender'].str.lower()

print(df['gender'])

0          male
1         other
2          male
3         other
4        female
          ...
19995     other
19996      male
19997     other
19998      male
19999      male
Name: gender, Length: 20000, dtype: object

In [17]:
a = np.array([[10, 20, 30],
              [40, 50, 60]])

print(a)
print("Shape:", a.shape)
print("Size:", a.size)
print("Dimension:", a.ndim)

[[10 20 30]
 [40 50 60]]
Shape: (2, 3)
Size: 6
Dimension: 2

In [18]:
import numpy as np
import pandas as pd

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

NumPy version: 2.1.3
Pandas version: 2.2.3

In [ ]:
a = np.array([[10, 20, 30],
              [40, 50, 60]])

print(a)
print("Shape:", a.shape)

[[10 20 30]
 [40 50 60]]
Shape: (2, 3)

In [ ]:
print(np)

<module 'numpy' from '/usr/local/lib/python3.13/dist-packages/numpy/__init__.py'>

In [19]:
# Fill missing numerical values
for col in df.select_dtypes(include=np.number).columns:
    df[col] = df[col].fillna(df[col].median())

# Fill missing categorical values
for col in df.select_dtypes(include=['object', 'category']).columns:
    if df[col].isnull().any() and not df[col].mode().empty:
        df[col] = df[col].fillna(df[col].mode()[0])

In [20]:
# Count duplicate rows
print("Duplicates:", df.duplicated().sum())

# Remove duplicate rows
df = df.drop_duplicates()

# Check updated shape
print(df.shape)

Duplicates: 0
(20000, 15)

In [21]:
# Remove extra spaces and convert text to lowercase
for col in df.select_dtypes(include=['object', 'category']).columns:
    df[col] = df[col].apply(
        lambda x: x.strip().lower() if isinstance(x, str) else x
    )

# Display cleaned data
print(df.head())

   student_id  age  gender    course      year parent_education  \
0      200.99   17    male  pharmacy  1st year      high school
1      200.99   23   other   diploma  2nd year      high school
2      200.99   22    male      b.sc  3rd year        no formal
3      200.99   20   other  pharmacy  2nd year        no formal
4      200.99   20  female  pharmacy  1st year        no formal

  internet_access hostel_resident class_type weather  study_hours  \
0              no             yes    offline   sunny         3.63
1             yes             yes    offline  cloudy         4.39
2             yes             yes     online   rainy         5.43
3             yes             yes    offline  cloudy         0.21
4             yes             yes     online   sunny         1.77

   sleep_hours  travel_time_minutes  attendance absence_reason
0         7.24                   31           1           none
1         7.98                   50           0      no reason
2         6.53                   62           1           none
3         7.11                   63           0  personal work
4         9.35                   81           0   project work

In [22]:
# Check unique values in categorical columns
for col in df.select_dtypes(include=['object', 'category']).columns:
    print(col, ":", df[col].unique())

# Check numerical statistics
print(df.describe())

gender : ['male' 'other' 'female']
course : ['pharmacy' 'diploma' 'b.sc' 'b.tech' 'b.com' 'nursing' 'bca' 'bba' 'ba']
year : ['1st year' '2nd year' '3rd year' '4th year']
parent_education : ['high school' 'no formal' 'phd' 'post graduate' 'graduate']
internet_access : ['no' 'yes']
hostel_resident : ['yes' 'no']
class_type : ['offline' 'online']
weather : ['sunny' 'cloudy' 'rainy' 'hot' 'cold']
absence_reason : ['none' 'no reason' 'personal work' 'project work' 'travel' 'sick'
 'festival']
         student_id           age   study_hours   sleep_hours  \
count  20000.000000  20000.000000  20000.000000  20000.000000
mean   10000.500000     20.473300      2.989558      7.013978
std     5770.211372      2.284458      1.727470      1.739200
min      200.990000     17.000000      0.050000      4.060000
25%     5000.750000     18.000000      1.480000      5.500000
50%    10000.500000     20.000000      2.980000      7.010000
75%    15000.250000     22.000000      4.480000      8.540000
max    19800.010000     24.000000      5.930000      9.940000

       travel_time_minutes    attendance
count         20000.000000  20000.000000
mean             46.978100      0.516350
std              24.583225      0.499745
min               5.000000      0.000000
25%              26.000000      0.000000
50%              47.000000      1.000000
75%              68.000000      1.000000
max              89.000000      1.000000

In [23]:
# Convert categorical columns into numerical columns
df_encoded = pd.get_dummies(
    df,
    columns=df.select_dtypes(include=['object', 'category']).columns,
    dtype=int
)

# Display encoded data
print(df_encoded.head())

# Check final shape
print(df_encoded.shape)

   student_id  age  study_hours  sleep_hours  travel_time_minutes  attendance  \
0      200.99   17         3.63         7.24                   31           1
1      200.99   23         4.39         7.98                   50           0
2      200.99   22         5.43         6.53                   62           1
3      200.99   20         0.21         7.11                   63           0
4      200.99   20         1.77         9.35                   81           0

   gender_female  gender_male  gender_other  course_b.com  ...  weather_hot  \
0              0            1             0             0  ...            0
1              0            0             1             0  ...            0
2              0            1             0             0  ...            0
3              0            0             1             0  ...            0
4              1            0             0             0  ...            0

   weather_rainy  weather_sunny  absence_reason_festival  \
0              0              1                        0
1              0              0                        0
2              1              0                        0
3              0              0                        0
4              0              1                        0

   absence_reason_no reason  absence_reason_none  \
0                         0                    1
1                         1                    0
2                         0                    1
3                         0                    0
4                         0                    0

   absence_reason_personal work  absence_reason_project work  \
0                             0                            0
1                             0                            0
2                             0                            0
3                             1                            0
4                             0                            1

   absence_reason_sick  absence_reason_travel
0                    0                      0
1                    0                      0
2                    0                      0
3                    0                      0
4                    0                      0

[5 rows x 45 columns]
(20000, 45)

In [24]:
# Final dataset information
print("Dataset shape:", df_encoded.shape)

# Check missing values
print("Missing values:", df_encoded.isnull().sum().sum())

# Check duplicate rows
print("Duplicate rows:", df_encoded.duplicated().sum())

# Display final data
print(df_encoded.head())

Dataset shape: (20000, 45)
Missing values: 0
Duplicate rows: 0
   student_id  age  study_hours  sleep_hours  travel_time_minutes  attendance  \
0      200.99   17         3.63         7.24                   31           1
1      200.99   23         4.39         7.98                   50           0
2      200.99   22         5.43         6.53                   62           1
3      200.99   20         0.21         7.11                   63           0
4      200.99   20         1.77         9.35                   81           0

   gender_female  gender_male  gender_other  course_b.com  ...  weather_hot  \
0              0            1             0             0  ...            0
1              0            0             1             0  ...            0
2              0            1             0             0  ...            0
3              0            0             1             0  ...            0
4              1            0             0             0  ...            0

   weather_rainy  weather_sunny  absence_reason_festival  \
0              0              1                        0
1              0              0                        0
2              1              0                        0
3              0              0                        0
4              0              1                        0

   absence_reason_no reason  absence_reason_none  \
0                         0                    1
1                         1                    0
2                         0                    1
3                         0                    0
4                         0                    0

   absence_reason_personal work  absence_reason_project work  \
0                             0                            0
1                             0                            0
2                             0                            0
3                             1                            0
4                             0                            1

   absence_reason_sick  absence_reason_travel
0                    0                      0
1                    0                      0
2                    0                      0
3                    0                      0
4                    0                      0

[5 rows x 45 columns]